id: run-0
status: complete
description: >
  General development and testing of the global-fit infrastructure.

date_begin: "2026-05"
date_end: "2026-05"

code:
  tag: cdl1-run0
  phentax_version: 0.1.1b4
  code_link: https://github.com/Erebor-L2D/LISAanalysistools

sources: [PSD]
dataset: simulated
observation_time: ""

results:
  cluster_paths: []
  cloud_urls: []

config: ""
contact: ""
plots: []
